### PR TITLE
Update TribeHR style guide CSS link to use HTTPS address

### PR DESCRIPTION
**Pull request by ianring**
the SSL cert is in place now, and I've verified that the URL is working.
https://media.tribehr.com/partners/panels/tribehr_panel_styles.css

### CODE REVIEW

**Comment by SimonClark** [comment]
:+1:

**Comment by KoryHodgson** [comment]
:+1: :100:

**Comment by KoryHodgson** [comment]
@ianring I don't have merge perms to this repo, so go for it

**Comment by ianring** [comment]
flexing some seldomly used git muscles...
```
git commit --amend -m "new commit message"
git push -f origin branch-name
```

**Comment by iniq** [comment]
Merging.

**Pull request merged**
